apiVersion: apps/v1
kind: Deployment
metadata:
  name: caesar-front
  labels:
    app: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: front-app-nginx
          image: ghcr.io/kiruha01/gnc-kuber-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

