name: Deploy to GitHub Registry

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Back Docker image
        run: docker build -t ghcr.io/${{ env.REPO }}-back:latest ./back
        
      - name: Build Front Docker image
        run: docker build -t ghcr.io/${{ env.REPO }}-front:latest ./front

      - name: Push Docker images to GitHub Registry
        run: |
          docker push ghcr.io/${{ env.REPO }}-back:latest
          docker push ghcr.io/${{ env.REPO }}-front:latest
